### ISSUE TITLE
Issues launching ios app

### ISSUE THREAD

**Issue by rbains4** [navneet-kumar/MyClinic#8]
Hello,
 After there was an update to this repository, I cloned it but I was not able to run the app successfully using "npm start" (after running npm install) on my Mac. The metro bundler pops up on my terminal but there is no option to run the simulator. Please let me know if there are any suggestions on how to get the updated app to work on a mac. It worked with your previous version. 

Thank you for your time, 
 Ravneel Bains

**Comment by navneet-kumar** [comment]
@rbains4, 

clean old version build using `rm -rf ios/build`
just run `react-native run-ios` on a seprate terminal.

Also delete old version on simulator if present.

**Comment by rbains4** [comment]
thank you for your suggestion.
